#!/usr/bin/perl
use File::Basename;
use File::Path;
$repo = dirname($0);
system("cp $repo/rtexec.pf rtexec.pf") unless(-e "rtexec.pf");
mkpath(qw(1mindata bin logs pf db dbmaster rtsys state www), {
 verbose => 1,
 mode => 0755,
 });
print<<"EOF";
Make sure that db points to a valid waveform data source.
And dbmaster points to a valid master_stations database.
And www points to where the plots should be on the webserver.
You will also need $0/pf in your PFPATH in rtexec.pf and
possibly in your shell rc file.
And you will need addpath(genpath($0/data/matlab) in your
Matlab startup file, or possibly in your rtrun_matlab
pf file.
  
EOF

