<?php
include('./includes/antelope.inc');

$page_title = 'Spectrogram Mosaic';
$css = array( "style2.css" );
$googlemaps = 0;
$js = array();

// Standard XHTML header
include('./includes/header.inc');

?>

<body bgcolor="#FFFFFF">

<?php

	# global variables
	$debugging = 0;


	# header files
	include('./includes/daysPerMonth.inc');
	include('./includes/mosaicMaker.inc');

	# Set date/time now
	$timenow = now();
	$currentYear = epoch2str($timenow, "%Y");
	$currentMonth = epoch2str($timenow, "%m");
	$currentDay = epoch2str($timenow, "%d");
	$currentHour = epoch2str($timenow, "%H");
#	$currentMinute = epoch2str($timenow, "%i);


	# Set convenience variables from CGI parameters
	$subnet = !isset($_REQUEST['subnet'])? $subnets[0] : $_REQUEST['subnet'];
	$year = !isset($_REQUEST['year'])? $currentYear : $_REQUEST['year'];
	$month = !isset($_REQUEST['month'])? $currentMonth : $_REQUEST['month'];
	$day = !isset($_REQUEST['day'])? $currentDay : $_REQUEST['day'];
	$hour = !isset($_REQUEST['hour'])? $currentHour : $_REQUEST['hour'];
	$minute = !isset($_REQUEST['minute'])? "00" : $_REQUEST['minute'];
	$numhours = !isset($_REQUEST['numhours'])? 2 : $_REQUEST['numhours'];
		
	# Degugging
	if ($debugging == 1) {
		echo "<p>subnet = $subnet</p>\n";
		echo "<p>year = $year</p>\n";
		echo "<p>month = $month</p>\n";
		echo "<p>day = $day</p>\n";
		echo "<p>hour = $hour</p>\n";
#		echo "<p>minute = $minute</p>\n";
		echo "<p>hour = $hour</p>\n";
		echo "<hr/>\n";
	}

	# Start page
	#echo "<h1>Mosaic Maker</h1>";


	# Horizontal rule
	print "<hr />";

 
	if(isset($_REQUEST["subnet"])) {
		if (isset($_REQUEST["year"]) && isset($_REQUEST["month"]) && isset($_REQUEST["day"]) && isset($_REQUEST["hour"])  && isset($_REQUEST["numhours"])  ) {

			# make sure the date is valid
			if(!checkdate($month,$day,$year)){
				echo "<p>invalid date</p>";
 			}
			else
			{

				# generate the epoch time now
				$timenow   = time(); # seconds # get utc/local conversion issues
				$timenow = now();
	
				# generate the epoch time for the start date/time requested
				#$starttime = mktime($hour, $minute, 0, $month, $day, $year); # get local/utc conversion issues
				$starttime = str2epoch("$year/$month/$day $hour:$minute:00");
			#	echo "<p>Starttime: $starttime, timenow: $timenow</p>";	
				if ($timenow > $starttime) {
				
					# work out the difference in seconds
					$starthour = (($timenow - $starttime) / 3600);
					$endhour   = (($timenow - $starttime) / 3600) - $numhours;
					mosaicMaker($subnet, $starthour, $endhour, $WEBPLOTS);
				}
				else
				{
					echo "<p>Date/Time entered must be in the past</p>\n";
				}
			}
		} 
	}
	else
	{

		echo "<h1>Welcome to the Spectrogram Mosaic Maker!</h1><p>This page is a link to pre-generated jpeg files generated by the Matlab program iceweb.m which runs every 10 minutes, generating static content to aid rapid response</p>";
#		$subnet = ""; $starthour = 2; $endhour = 0;
#		$_REQUEST["subnet"]=""; $_REQUEST["starthour"]=""; $_REQUEST["endhour"]=""; 


	}


	# THE FORM
	echo "<hr>\n";


	# Start form
	echo "<form method=\"get\"> ";

	# Start table
	echo "<table>\n\n";

	# Subnet widgit
	echo "<tr><td>Subnet</td>\n";
	echo "<td><select name=\"subnet\"> ";
	echo "<option value=\"$subnet\" SELECTED>$subnet</option>";
	foreach ($subnets as $subnet_option) {
		print "<option value=\"$subnet_option\">$subnet_option</option> ";
	}
	print "</select>";
	echo "</td></tr>\n";

	################## START TIME
	echo "<tr><td>Start time (UTC):</td><td>\n";
	# start new table inside this cell
	echo "<table><tr>\n";

	# Year widgit
	echo "<td>Year:</td>\n";
	echo "<td><input type=\"text\" name=\"year\" value=\"$year\" size=\"4\"> ";
	echo "</td>\n";

	# Month widgit
	echo "<td>Month:</td>\n";
	echo "<td><input type=\"text\" name=\"month\" value=\"$month\" size=\"2\"> ";
	echo "</td>\n";

	# Day widgit
	echo "<td>Day:</td>\n";
	echo "<td><input type=\"text\" name=\"day\" value=\"$day\" size=\"2\"> ";
	echo "</td>\n";

	# Hour widgit
	echo "<td>Hour:</td>\n";
	echo "<td><input type=\"text\" name=\"hour\" value=\"$hour\" size=\"2\"> ";
	echo "</td>\n";

	# Minute widgit
	echo "<td>Minute:</td>\n";
	echo "<td><select name=\"minute\"> ";
	echo "<option value=\"$minute\" SELECTED>$minute</option>";
	$minutes = array("00", "10", "20", "30", "40", "50");
	foreach ($minutes as $minute_option) {
		print "<option value=\"$minute_option\">$minute_option</option> ";
	}
	print "</select>";
	echo "</td>\n";

	# end this table
	echo "</tr></table>\n";

	# end this cell and row
	echo "</td></tr>\n";
	###################### END OF START TIME

	# Number of hours widgit
	echo "<tr><td>Number of hours:</td>\n";
	echo "<td><input type=\"text\" name=\"numhours\" value=\"$numhours\" size=\"2\"> ";
	echo "</td></tr>\n";

	# Submit & Reset buttons
	echo "<tr>\n";
	print "<td><input type=\"submit\" name=\"submit\" value=\"Make Mosaic\"></td>\n";
#	print "<td><input type=\"reset\" name=\"reset\" value=\"reset\"></td>\n";
	print "<td><a href=\"mosaicMakerHoursAgo.php?subnet=$subnet&starthour=$starthour&endhour=$endhour\">Select by hours ago</a></td>\n";

	echo "</tr>\n";

	# End the table
	echo "</table>\n";


	# End form
	echo "</form>\n";


?>


<div><script language="Javascript" type="text/javascript">now = new Date;document.write("<p>Generated: " + now.toUTCString()  + "</p>");</script></div>

</body>
</html>



